version: '3.8'

services:
  mysql-master:
    image: mariadb
    container_name: mysql-master
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: test_db
    volumes:
      - ./config/mysql/my.cnf-master:/etc/my.cnf
      - ./data/master:/var/lib/mysql
    networks:
      - docker-network

  mysql-replica1:
    image: mariadb
    container_name: mysql-replica1
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_DATABASE: test_db
    depends_on:
      - mysql-master
    volumes:
      - ./config/mysql/my.cnf-slave1:/etc/my.cnf
      - ./data/slave1:/var/lib/mysql
    networks:
      - docker-network

  mysql-replica2:
    image: mariadb 
    container_name: mysql-replica2
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: test_db
    depends_on:
      - mysql-master
    volumes:
      - ./config/mysql/my.cnf-slave2:/etc/my.cnf
      - ./data/slave2:/var/lib/mysql
    networks:
      - docker-network  

  proxysql:
    image: proxysql/proxysql:latest
    container_name: proxysql
    ports:
      - "6032:6032" # Admin port
      - "6033:6033" # MySQL port
    volumes:
      - ./data/proxysql:/var/lib/proxysql
      - ./config/proxysql/proxysql.cnf:/etc/proxysql.cnf
    depends_on:
      - mysql-master
    networks:
      - docker-network
    restart: always

  orchestrator:
    image: percona/percona-orchestrator
    container_name: orchestrator
    ports:
      - "3000:3000"
    volumes:
      - ./config/orchestrator/orchestrator.cnf:/etc/orchestrator/orchestrator.conf.json
      - ./config/orchestrator/orc-topology.cnf:/etc/orc-topology.cnf
    networks:
      - docker-network

  percona-toolkit:
    image: perconalab/percona-toolkit
    container_name: percona-toolkit
    ports:
      - "3100:3100"
    networks:
      - docker-network

networks:
  docker-network:
