version: '3.8'

services:
  mysql-master:
    image: mysql/mysql-server:8.0
    container_name: mysql-master
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: test_db
    volumes:
      - ./config/mysql/my.cnf-master:/etc/mysql/my.cnf
      - ./data/master:/var/lib/mysql
    networks:
      - docker-network

  mysql-replica1:
    image: mysql/mysql-server:8.0
    container_name: mysql-replica1
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_DATABASE: test_db
    depends_on:
      - mysql-master
    volumes:
      - ./config/mysql/my.cnf-slave1:/etc/mysql/my.cnf
      - ./data/slave1:/var/lib/mysql
    networks:
      - docker-network

  mysql-replica2:
    image: mysql/mysql-server:8.0 
    container_name: mysql-replica2
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: test_db
    depends_on:
      - mysql-master
    volumes:
      - ./config/mysql/my.cnf-slave2:/etc/mysql/my.cnf
      - ./data/slave2:/var/lib/mysql
    networks:
      - docker-network  

  orchestrator:
    image: openarkcode/orchestrator
    container_name: orchestrator
    ports:
      - "3000:3000"
    volumes:
      - ./config/orchestrator/orchestrator.cnf:/etc/orchestrator.conf.json
    networks:
      - docker-network

  percona-toolkit:
    image: perconalab/percona-toolkit
    container_name: percona-toolkit
    ports:
      - "3100:3100"
    networks:
      - docker-network

networks:
  docker-network:
